In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()

# Load Dataset
df = pd.read_csv("/Users/kritinshanmugam/Desktop/palmer_penguins.csv")


# Get data only related to sepal
target_df = df[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g', 'species']]

# Species Name
target_df['species'].unique()


array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [57]:
target_df = target_df.dropna()

# Select only rows from target_data where the species is setosa or versicolor
target_df = target_df[target_df['species'].isin(['Chinstrap', 'Gentoo'])]

target_df['species'] = np.where(target_df['species'] == 'Chinstrap', 1, -1)

X = target_df[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g', 'species']].values
y = target_df['species'].values

print(X, y)


[[ 4.650e+01  1.790e+01  1.920e+02  3.500e+03  1.000e+00]
 [ 5.000e+01  1.950e+01  1.960e+02  3.900e+03  1.000e+00]
 [ 5.130e+01  1.920e+01  1.930e+02  3.650e+03  1.000e+00]
 [ 4.540e+01  1.870e+01  1.880e+02  3.525e+03  1.000e+00]
 [ 5.270e+01  1.980e+01  1.970e+02  3.725e+03  1.000e+00]
 [ 4.520e+01  1.780e+01  1.980e+02  3.950e+03  1.000e+00]
 [ 4.610e+01  1.820e+01  1.780e+02  3.250e+03  1.000e+00]
 [ 5.130e+01  1.820e+01  1.970e+02  3.750e+03  1.000e+00]
 [ 4.600e+01  1.890e+01  1.950e+02  4.150e+03  1.000e+00]
 [ 5.130e+01  1.990e+01  1.980e+02  3.700e+03  1.000e+00]
 [ 4.660e+01  1.780e+01  1.930e+02  3.800e+03  1.000e+00]
 [ 5.170e+01  2.030e+01  1.940e+02  3.775e+03  1.000e+00]
 [ 4.700e+01  1.730e+01  1.850e+02  3.700e+03  1.000e+00]
 [ 5.200e+01  1.810e+01  2.010e+02  4.050e+03  1.000e+00]
 [ 4.590e+01  1.710e+01  1.900e+02  3.575e+03  1.000e+00]
 [ 5.050e+01  1.960e+01  2.010e+02  4.050e+03  1.000e+00]
 [ 5.030e+01  2.000e+01  1.970e+02  3.300e+03  1.000e+00]
 [ 5.800e+01  

In [58]:
class Perceptron(object):
    def __init__(self, eta = 0.5, epochs = 50):
        self.eta = eta
        self.epochs = epochs
    
    def train(self, X, y):
        self.w_ = np.random.rand(1 + X.shape[1])
        
        self.errors_ = []
        
        for _ in range(self.epochs):
            errors = 0
            for xi, target in zip(X, y):
                update = self.eta * (self.predict(xi) - target)
                self.w_[:-1] -= update*xi
                self.w_[-1] -= update
                errors += int(update != 0)
                if errors == 0:
                    return self
                else:
                    return self.errors_.append(errors)
        
        return self
    
    def net_input(self, X):
        return np.dot(X, self.w_[:-1]) + self.w_[-1]
    
    def predict(self, X):
        return np.where(self.net_input(X) >= 0, 1, -1)

In [61]:
from sklearn.model_selection import train_test_split

# Create instance of Perceptron class with 10k epochs
Percept = Perceptron(epochs = 10_000)

# Split dataset into training and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25)

# Train the Perceptron on the training dataset
Percept.train(X_train, y_train)

# Obtain the predictions
y_predictions = Percept.predict(X_test)

booleans = ((y_test == y_predictions))

print(np.sum(booleans == False))

31
